name: fiscalrag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - camelot-py
  - ghostscript
  - llama-index
  - ollama-0.4.7
  - pandas
  - jupyterlab
  - python-dotenv
  - pip
  - pip:
    - PyPDF2
    - llama-index
    - ollama           # Apenas se usar modelos locais
    - python-dotenv
    - opencv-python
    - llama-index-embeddings-huggingface
    - transformers
    - sentence-transformers 
    - torch
